CREATE TABLE "GCG_6273_L_PART_FRAG"(
 "IDENTIFIER" CHAR(20),
 "ID_NUM" CHAR(8),
 "L_PART_FRAG" CHAR(20),
 "BASE_ID" CHAR(20),
 "PARENT_ID" CHAR(8));

CREATE INDEX "GCG_6273_L_PART_FRAG" ON "GCG_6273_L_PART_FRAG"("IDENTIFIER", "ID_NUM","BASE_ID","PARENT_ID");